Update codeql.yml
try increasing build coverage

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -65,20 +65,48 @@ jobs:
 
 
     # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
-    # If this step fails, then you should remove it and run the build manually (see below)
     - name: Autobuild
       uses: github/codeql-action/autobuild@v2
 
-    # Command-line programs to run using the OS shell.
-    # See:
-    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-
-    #   If the Autobuild fails above, remove it and uncomment the following three lines.
-    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
-
-    # - run: |
-    #     echo "Run, Build Application using script"
-    #     ./location_of_script_within_repo/buildscript.sh
+    - name: Extra coverage build
+      if: success()
+      run: |
+        if test -r Makefile; then (make check && make distcheck); fi
+        # shellcheck disable=SC2001,SC2235
+        for subdir in example include src src/lzfse tools; do \
+          if test -e "${subdir}/Makefile"; then \
+            pushd "${subdir}"; \
+            for srcfile in *.c; do \
+              echo "attempting to use $(which make) to compile ${srcfile} in ${subdir}"; \
+              make "$(echo "${srcfile}" | sed "s/\.c/.o/g")" V=0 CFLAGS="-w" || stat -t "${srcfile}"; \
+            done; \
+            popd; \
+          elif test -d "${subdir}" && (test -r "${subdir}/Makefile.in" || test -r "${subdir}/Makefile.am"); then \
+            echo "no unsuffixed Makefile in ${subdir}, but there are these ones with suffixes:"; \
+            ls ${subdir}/Makefile* || echo "... $(ls ${subdir}/Makefile*)"; \
+          else \
+            echo "skipping attempting to build additional objfiles in ${subdir}"; \
+          fi; \
+        done
+        (time (find . -name '*.o' -exec cp -v {} . ";")) || echo "failed copying an object file"
+        FINAL_CPPFLAGS="-I."
+        for myincdir in include include/applefw src/lzfse; do \
+          if test -d "${myincdir}" && test -r "${myincdir}" && test -n "$(ls "${myincdir}"/*.h)"; then \
+            FINAL_CPPFLAGS="${FINAL_CPPFLAGS} -I${myincdir} -iquote ${myincdir}"; \
+          fi; \
+        done
+        echo "FINAL_CPPFLAGS are ${FINAL_CPPFLAGS}"
+        # shellcheck disable=SC2001,SC2044
+        for cfile in $(find . -name '*.c' -type f); do \
+          cobjfile="$(echo "${cfile}" | sed "s/\.c/.o/g")"; \
+          if test ! -e "${cobjfile}"; then \
+            echo "gcc -c -w \"${FINAL_CPPFLAGS}\" \"${cfile}\""; \
+            gcc -c -w "${FINAL_CPPFLAGS}" "${cfile}" || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
+          else \
+            echo "object file ${cobjfile} already exists for ${cfile}."; \
+            cp -v "${cobjfile}" "$(dirname "${cfile}")" || cp -v "${cobjfile}" . || cp -v "${cobjfile}" .. || (if test -d /tmp && test -w /tmp; then cp -v "${cobjfile}" /tmp; fi) || stat -t "${cobjfile}"; \
+          fi; \
+        done
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v2
